services:
  postgresql:
    container_name: banco_hotel
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=reservaHotel
    volumes:
      - postgres_data:/bitnami/postgresql
  minio:
    container_name: hotel_files_minio
    hostname: minio
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9003:9000"
      - "9005:9001"
    env_file:
      - minio.env
    volumes:
      - hotel_files_minio_volume:/data
    networks:
      - hotel_files_minio_stack

networks:
  hotel_files_minio_stack:

volumes:
  postgres_data:
    driver: local
  hotel_files_minio_volume: