ALTER TABLE room
ADD COLUMN bed_config VARCHAR(255) NOT NULL DEFAULT 'Não configurado',
ADD COLUMN amenities TEXT NOT NULL DEFAULT 'Nenhum',
ADD COLUMN capacity INTEGER NOT NULL DEFAULT 1,
ADD COLUMN category VARCHAR(100) NOT NULL DEFAULT 'STD',
DROP COLUMN room_type_id CASCADE;

DROP TABLE room_type;